### ISSUE TITLE
downsample_cvae

### ISSUE THREAD

**Issue by zengliangjun** [AlbertTan404/RoLD#1]
where is downsample_cvae.yaml

**Comment by AlbertTan404** [comment]
> where is downsample_cvae.yaml

Thank you for your interest in our project. We are currently organizing other files, which will be released subsequently.

**Comment by AlbertTan404** [comment]
> where is downsample_cvae.yaml

Sorry for the late response. Something's wrong with our submission on blinding, so we are considering reconstruct the project. We'll open the code upon next submission.
