### ISSUE TITLE
Is evaluation code included?

### ISSUE THREAD

**Issue by zhiyuan-zhang0206** [AlbertTan404/RoLD#2]
Hi, 
Thanks for your amazing work, and open-sourcing your code!

I wonder if the evaluation code is included in the repo now. I tried to locate those scripts but no luck. If they are not released yet, do you have any plans for releasing the evaluation scripts?

Thanks in advance.

**Comment by AlbertTan404** [comment]
Thank you for your attention to our work! We are still cleaning the code and optimizing the backend of evaluator and we will release the remaining code altogether (but it may take a long time cuz we are primarily working on another project now). You could refer to diffusion-policy and vc-1 for relevant code :)

**Comment by zhiyuan-zhang0206** [comment]
> Thank you for your attention to our work! We are still cleaning the code and optimizing the backend of evaluator and we will release the remaining code altogether (but it may take a long time cuz we are primarily working on another project now). You could refer to diffusion-policy and vc-1 for relevant code :)

Thanks for the timely reply! Will check the DP code.
