### ISSUE TITLE
Multitask evaluation model configuration

### ISSUE THREAD

**Issue by zhiyuan-zhang0206** [AlbertTan404/RoLD#3]
Hi,
May I ask how did you adapt DiffusionPolicy and ACT to multi-task settings? Did you just "tell" the model that the task is different purely by different visual observations? In the paper you mentioned that DP performed much poorer under multi-task settings.
Thanks in advance.

**Comment by AlbertTan404** [comment]
Hi Zhiyuan,
All of the multi-task experiments are conducted under the same condition: observation and textual instruction, and the latter one is more important for multitasking. DP has excellent performances on single-task policy modeling, but indeed, multi-task policy modeling requires more specific design like our decoupled action and policy modeling :)

**Comment by zhiyuan-zhang0206** [comment]
Thanks for your quick response! Closing the issue.
